### ISSUE TITLE
Add support for applying attributes within ranges.

### ISSUE THREAD

**Issue by Nirma** [Nirma/Attributed#11]
As the implementation of the library now stands creating an attributed string composed of different attributes can be done with the addition operator like so:

```swift
let baseAttributes = Attributes().font(UIFont(name: "Chalkduster", size: 24.0)!)
let accentedAttributes = baseAttribues.foreground(color: .red) 
                                      .underlineStyle(.styleSingle)

let partOne = "Hello, ".attributed(with: baseAttributes) 
let partTwo = "World!".attributed(with: accentedAttributes)
let attributedString = partOne + partTwo
```

This works, albeit inconvenient.

Adding functionality to the library that supports applying attributes to ranges would make this task much easier. 
Perhaps something like the following:

```swift
let baseAttributes = Attributes().font(UIFont(name: "Chalkduster", size: 24.0)!)
let accentedAttributes = baseAttribues.foreground(color: .red) 
                                      .underlineStyle(.styleSingle)

"Hello, World!".attributed(with: [(0..5, baseAttributes ), accentedAttributes])
```

Where the text with different attributes is specified with a range and attributes and then the remainder of the text is attributed with the attributes contained in the tuple with the `nil` range.

**Comment by vfn** [comment]
@Nirma, PR https://github.com/Nirma/Attributed/pull/12 tackles a similar issue. I didn't try to work on an API similar to the one you suggested, because of the non-compatibility in between `Range` and `NSRange`, and unfortunately, `NSAttributedString` only works with `NSRange`s.

**Comment by Nirma** [comment]
I am going to close this for now, I am more open to implementing support for ranged attributes
in a different way than when I opened this issue.
