### ISSUE TITLE
No method for NSBaselineOffsetAttributeName?

### ISSUE THREAD

**Issue by kidsid-Ixigo** [Nirma/Attributed#35]
I have searched through the documents and files but didn't get any method for NSBaselineOffsetAttributeName. Is it not there?

**Comment by Nirma** [comment]
@kidsid-Ixigo Thanks for pointing that out! Yes `NSBaselineOffsetAttributeName` support is currently missing, my mistake.

I will get around to putting out a release soon!

If anyone wants to send over a pull request in the meantime that is fine as well!
