### ISSUE TITLE
set internal dictionary property Public

### ISSUE THREAD

**Issue by haashem** [Nirma/Attributed#37]
in some scenarios I need to access internal dictionary.
for example:

``` swift 
let attributes = Attributes {
            return $0.foreground(color: .white)
            .alignment(.center)
            .font(UIFont.DinCondensedBold(of: 17))
        }
        
        let icon = String(value)
        // Get the width and height that the text will occupy.
        let iconSize = icon.size(attributes: attributes)
        
        icon.draw(in:
            CGRect(x: (size.width - iconSize.width)/2.0, y: (size.height - iconSize.height)/2.0, width: iconSize.width, height: iconSize.height),
                  withAttributes: attributes.dictionary)
```

but dictionary property is internal.

**Comment by Nirma** [comment]
@hashemp206 Thanks for opening the issue! 

Im going to go through the implementation and think about opening the internal dictionary. 
If it makes sense then Ill have a release out shortly. 

👍

**Comment by erikolsson** [comment]
Thanks for a great lib!

I second this, size calculations are impossible without a public dictionary. Any updates on this?

**Comment by Nirma** [comment]
@hashemp206  @erikolsson Ok lets do it! 

@erikolsson I can make it public and test it but if you feel up to it you are more than welcome to send over a pull request!

**Comment by Nirma** [comment]
@hashemp206 @erikolsson Finally got this done! 

Its included in the latest release here:

https://github.com/Nirma/Attributed/releases/tag/2.1.0

**Comment by erikolsson** [comment]
Amazing, thank you very much!! Sorry for not compiling a PR, I didn't find the time unfortunately!
