### ISSUE TITLE
Could check out Attributed with Carthage

### ISSUE THREAD

**Issue by dungi** [Nirma/Attributed#41]
> Attributes.swift:92:47: error: 'NSBaselineOffsetAttributeName' has been renamed to 'NSAttributedStringKey.baselineOffset'
>         return self + Attributes(dictionary: [NSBaselineOffsetAttributeName: offset])
>                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                               NSAttributedStringKey.baselineOffset
> UIKit.NSBaselineOffsetAttributeName:3:12: note: 'NSBaselineOffsetAttributeName' was obsoleted in Swift 3
> public let NSBaselineOffsetAttributeName: NSAttributedStringKey

**Comment by gregpardo** [comment]
This is the change that was just merged in. Hopefully new build is ready soon.

**Comment by dungi** [comment]
ah :) so I check out this commit - thanks

**Comment by Nirma** [comment]
@dunqi @gregpardo I just put out a release! This should be fixed in:

https://github.com/Nirma/Attributed/releases/tag/2.0.1

How is the issue now?

**Comment by dungi** [comment]
Works fine
