### ISSUE TITLE
change an attribute of attributedString

### ISSUE THREAD

**Issue by haashem** [Nirma/Attributed#44]
consider this scenario:
I have set an attributedText for UILabel

then later based on a condition I need only to change the textColor.

what I'm looking for:
```swift
textLabel.at.change(.foregroundColor).to(.yellow)
```

whats your opinion?

what I do right now is:
```swift
var attributes = titleNode.attributedText?.attributes(at: 0, longestEffectiveRange: nil, in: NSMakeRange(0, titleNode.attributedText!.length))
            
            if isSelected {
                attributes?[NSAttributedStringKey.foregroundColor] = selectedTitleColor
            } else {
                attributes?[NSAttributedStringKey.foregroundColor] = normalTitleColor
            }
            
            titleNode.attributedText = NSAttributedString(string: title, attributes: attributes)
```

**Comment by Nirma** [comment]
@hashemp206 Right, I think thats a great idea. I have been meaning to add some functionality for in-place modification. If its ok maybe by the end of this week I plan on starting that development. 

Other than that you can feel free to go ahead and try sending over a pull request and we can work together to get it into shape and put out a release.
👍

**Comment by haashem** [comment]
that sounds good. I will try to make a pull request

**Comment by Nirma** [comment]
This is being tracked on #51 lets move the conversation over there!
