### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by vstepanyuk** [Nirma/Attributed#48]
```Pods/AttributedLib/Attributed/String+Attributed.swift:33:61: Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'```

```Pods/AttributedLib/Attributed/Attributes.swift:48:47: Type 'NSAttributedStringKey' (aka 'NSString') has no member 'kern'```

**Comment by Nirma** [comment]
@vstepanyuk Thanks so much for opening this! I just put out a new release how does it look now?

**Comment by vstepanyuk** [comment]
Thx. I’ll test

**Comment by Nirma** [comment]
This seems to be fixed now, so closing this issue. 

If something pops up again please feel free to open an issue.
