### ISSUE TITLE
I also can not fetch latest release version of this repo.

### ISSUE THREAD

**Issue by Arcovv** [Nirma/Attributed#59]
My `pod search AttributedLib` result:
```
-> AttributedLib (2.1.1)
   Modern Swift µframework for attributed strings.
   pod 'AttributedLib', '~> 2.1.1'
   - Homepage: https://github.com/Nirma/Attributed
   - Source:   https://github.com/Nirma/Attributed.git
   - Versions: 2.1.1, 2.1.0, 2.0.2, 2.0.1, 2.0.0, 1.3.0, 1.2.0, 1.1.0, 1.0.0,
   0.2.2, 0.2.1, 0.2.0, 0.1.1, 0.1.0 [master repo]
```

I think problem is in here:
```
s.source           = { :git => 'https://github.com/Nirma/Attributed.git', :tag => s.version.to_s }
```

I also check your tag position:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/11262771/47198225-95b82680-d39d-11e8-80eb-31f87b3712f9.png">

So I consider maybe you should move the tag at the correct place.

**Comment by Arcovv** [comment]
In my forked repo, I also check my tag position:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/11262771/47198289-fcd5db00-d39d-11e8-90be-a749e6bbe9db.png">

I can use my forked repo to fetch the latest AttributedLib framework~

**Comment by natan** [comment]
Indeed, it looks like the latest tag has not been published to Cocoapods. @Nirma Can you please do so?

In the meantime, one can temporarily workaround this issue with:

`pod 'AttributedLib', :git => 'https://github.com/Nirma/Attributed.git', :tag => '2.2.0'`

**Comment by natan** [comment]
@Nirma Any update on this?

**Comment by Nirma** [comment]
@Arcovv @natan Thank you so much for opening the issue. I have stepped away from this project for most of half of last year do to personal reasons but would like to step back in again and move forward. The latest version has been pushed to trunk! Please tell me if `pod update` works!

**Comment by Arcovv** [comment]
Hi @Nirma it's worked! Thank you!

**Comment by natan** [comment]
@Nirma Thank you.
