### ISSUE TITLE
Typo in `background(color: UIColor) -> Attributes`

### ISSUE THREAD

**Issue by andreyz** [Nirma/Attributed#6]
[This line](https://github.com/Nirma/Attributed/blob/master/Attributed/String%2BAttributed.swift#L57) should say `NSBackgroundColorAttributeName`.

**Comment by Nirma** [comment]
@andreyz Thanks so much for finding this!
Ill quickly get around to fixing it but if you or someone is up for it Id gladly accept a Pull Request!

**Comment by andreyz** [comment]
Just such a tiny edit, thought might be simpler for you :)
