### ISSUE TITLE
README: consider removing discussion of stale branches

### ISSUE THREAD

**Issue by natan** [Nirma/Attributed#62]
The bottom of the README contains mentions to `development`, `attributed-3.0` branches; but it appears that those are stale and all development is actually happening on `master` (which is fine). I was confused by this. Please consider removing the stale branches and this information from the README.

**Comment by Nirma** [comment]
@natan Good eye! I just did! Thanks so much for pointing this out!!

**Comment by natan** [comment]
@Nirma Thanks!
